CREATE TABLE IF NOT EXISTS person (
    id INT generated by default as identity PRIMARY KEY,
    name VARCHAR(10) NOT NULL,
    age INT NOT NULL
);

MERGE INTO person VALUES (1, 'soramame', 18);
MERGE INTO person VALUES (2, 'edamame', 32);
